Implement UI of group settings
InfuseAI/primehub-console pull request #182
Opened 2021-03-24 15:56 UTC by ctiml

- Add setting page
- Add info tab

Signed-off-by: Timothy Lee <ctiml@infuseai.io>

2021-03-30 10:30 UTC, ctiml commented
Test image: `ch16089-670250e3`

2021-03-30 10:42 UTC, ctiml commented
Test image: `ch16089-0daaa9b4`

2021-03-31 02:05 UTC, ctiml commented
Test image: `ch16089-a5729520`

2021-03-31 15:51 UTC, ctiml commented
Test image: `ch16089-0524d62a`

2021-03-31 17:09 UTC, ctiml commented
Test image: `ch16089-dba11d56`

2021-04-01 04:54 UTC, aar0nTw requested changes

2021-04-01 08:18 UTC, aar0nTw commented on packages/client/src/components/groupSettings/alert.tsx
> +           message='Only system admins can update these settings'
title: `These settings can be updated in Admin Portal`
desc: `Please update them in Admin Portal or contact the administrator.`

2021-04-01 08:30 UTC, merged