Model management UI
InfuseAI/primehub-console pull request #202
Opened 2021-04-27 02:44 UTC by popcornylu

2021-04-27 03:19 UTC, popcornylu commented
Could we change the learn more color to white?

![image](https://user-images.githubusercontent.com/860633/116179670-532feb80-a74a-11eb-95dc-7783898c07bb.png)

2021-04-28 04:04 UTC, aar0nTw commented
> Could we change the learn more color to white?
> 
> ![image](https://user-images.githubusercontent.com/860633/116179670-532feb80-a74a-11eb-95dc-7783898c07bb.png)

<Tooltip
      placement='right'
      title={<span>This is used to access the MLflow artifact stores, <a style={{color: '#739af3'}} target='_blank' href='https://www.mlflow.org/docs/latest/tracking.html#artifact-stores'>Learn more</a></span>}>
      <Icon type='question-circle' />
    </Tooltip>

2021-04-28 04:04 UTC, aar0nTw commented
> Could we change the learn more color to white?
> 
> ![image](https://user-images.githubusercontent.com/860633/116179670-532feb80-a74a-11eb-95dc-7783898c07bb.png)

Already updated

2021-05-03 08:30 UTC, aar0nTw requested changes
LG, only 3 comments for changes.

2021-05-03 08:30 UTC, aar0nTw commented on packages/client/src/components/share/breadcrumb.tsx
> +                !!onClick ? <a style={{color: (last) ? 'rgba(0, 0, 0, 0.65)' : null}} onClick={(e) => onClick()}>{title}</a> :
Just use `onClick={onClick}` is more flexible for the event handler.

2021-05-03 08:30 UTC, aar0nTw commented on packages/client/src/ee/components/modelMngt/common.ts
> +  if (Number.isNaN(n)) {
use `_.isNumber` can prevent `Infinity` `-Infinity` `NaN`

2021-05-03 08:30 UTC, aar0nTw commented on packages/client/src/ee/containers/modelDetail.tsx
> +    name: 'getModel'
Tips: add option `alias: 'withGetModel'` will easier determine the graphql context in react inspector.

2021-05-04 03:45 UTC, aar0nTw requested changes

2021-05-04 03:45 UTC, aar0nTw commented on packages/client/src/ee/components/modelMngt/common.ts
> +import isNumber from 'lodash'
`import {isNumber} from 'lodash'`

2021-05-05 00:47 UTC, popcornylu commented on packages/client/src/ee/components/modelMngt/common.ts
> +import isNumber from 'lodash'
Done

2021-05-05 01:53 UTC, aar0nTw approved these changes

2021-05-05 01:53 UTC, merged