Collect user feedback
InfuseAI/primehub-console pull request #334
Opened 2021-08-31 07:26 UTC by qrtt1

** PR checklist **

- [x] Ensure you have added or ran the appropriate tests for your PR.
- [x] DCO signed

**What type of PR is this?**

enhancement

**What this PR does / why we need it**:

collect user feedback

**Which issue(s) this PR fixes**:

ch20220

2021-09-01 07:15 UTC, popcornylu commented on packages/client/src/components/share/tracker.tsx
> +      <div>
return null or `<></>`

2021-09-01 09:06 UTC, aar0nTw requested changes

2021-09-01 09:06 UTC, aar0nTw commented on packages/client/src/components/share/tracker.tsx
> +import React from 'react';
Don't import same package twice, `import React, { useEffect, useState} from 'react'`

2021-09-01 09:06 UTC, aar0nTw commented on packages/client/src/components/share/tracker.tsx
> +  const analytics = window['analytics'] || null;
use window.analytics

2021-09-01 09:06 UTC, aar0nTw commented on packages/client/src/components/share/tracker.tsx
> +    return (<></>)
pls install prettier for ur editor

2021-09-01 09:12 UTC, aar0nTw requested changes

2021-09-01 09:12 UTC, aar0nTw commented on packages/client/src/components/share/tracker.tsx
> +
`const {collected, location, pageChanges} = state;`

2021-09-01 09:12 UTC, aar0nTw commented on packages/client/src/components/share/tracker.tsx
> +  const [display, setDisplay] = useState({ show: false, type: 'modal' });
u should separate to different states.

2021-09-01 09:37 UTC, poga commented
Wording:

Title: `Thanks for using PrimeHub! Any thing you want to share?`

link to twitter: `Share your experience to us on Twitter`
link to discord: `Join our Discord community`

2021-09-01 10:10 UTC, qrtt1 commented
@poga 

* prompt will not close automatically
* update new wording

![image](https://user-images.githubusercontent.com/193223/131653481-7ab67be1-aca2-4427-a381-5fe2811bdb9e.png)

![image](https://user-images.githubusercontent.com/193223/131653644-7e2f2660-b6f3-47cd-a0d3-a8577f292965.png)

2021-09-02 02:38 UTC, aar0nTw approved these changes
LGTM

2021-09-02 06:36 UTC, popcornylu commented
LGTM.

2021-09-02 08:39 UTC, merged