Feature/sc 22788/dataset v2 0 crud
InfuseAI/primehub-console pull request #426
Opened 2021-11-10 09:53 UTC by ctiml

**PR checklist**

- [x] Ensure you have added or ran the appropriate tests for your PR.
- [x] DCO signed

**What type of PR is this?**
Feature

**What this PR does / why we need it**:
Dataset 2.0 CRUD

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

2021-11-11 00:37 UTC, neighborhood999 commented on packages/client/src/containers/Datasets/DatasetList.tsx
> +  function renderTags(text, record) {
Seems the text not be used, you can change it as:

```suggestion
  function renderTags(record) {
```

And don't forget to delete Line 275 (`dataIndex`).

2021-11-11 06:07 UTC, popcornylu requested changes
Need to add dataset to `main.model_deploy.tsx`

2021-11-11 06:22 UTC, popcornylu requested changes
1. If there is a file in the `datasets` folder, it would crash the graphql.
2. If there is a folder in the `datasets/xxxx folder but no `.dataset` file, the graphql would fail.

```
6 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"}
/usr/src/app/packages/graphql-server/lib/resolvers/datasetV2.js:94
            const id = obj.prefix.replace(objectPrefix, '').slice(0, -1);
                                  ^

TypeError: Cannot read property 'replace' of undefined
    at Readable.<anonymous> (/usr/src/app/packages/graphql-server/lib/resolvers/datasetV2.js:94:35)
    at Readable.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Readable.push (internal/streams/readable.js:206:10)
    at Readable.readStream._read (/usr/src/app/node_modules/minio/dist/main/minio.js:1825:22)
    at DestroyableTransform.<anonymous> (/usr/src/app/node_modules/minio/dist/main/minio.js:1842:22)
    at DestroyableTransform.emit (events.js:400:28)
    at addChunk (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at DestroyableTransform.Readable.push (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at DestroyableTransform.Transform.push (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at DestroyableTransform._flush (/usr/src/app/node_modules/minio/dist/main/transformers.js:96:14)
    at DestroyableTransform.prefinish (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:129:10)
    at DestroyableTransform.emit (events.js:400:28)
    at prefinish (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:611:14)
```

2021-11-12 04:19 UTC, neighborhood999 commented
Conflict

2021-11-15 03:38 UTC, neighborhood999 commented on packages/client/src/ee/main.model_deploy.tsx
> +import { DatasetList, DatasetDetail } from 'containers/Datasets';
Should we align the import component by `import Component from '.../path'` this way?

2021-11-15 03:38 UTC, neighborhood999 commented on packages/client/src/components/datasets/CreateForm.tsx
> +  function genId(value: string) {
This is an independent function, you can move it outside the function component.

2021-11-15 03:38 UTC, neighborhood999 commented on packages/client/src/components/datasets/CreateForm.tsx
> +              await onSubmit({ id, name, tags });
Maybe add a `try/catch`?

2021-11-15 03:38 UTC, neighborhood999 commented on packages/client/src/containers/Datasets/DatasetDetail.tsx
> +type Props = {
Providing another option:

```ts
interface Props extends RouteComponentProps<{ datasetId: string }>, GroupContextComponentProps {
  // ...
}
```

2021-11-15 03:38 UTC, neighborhood999 commented on packages/client/src/containers/Datasets/DatasetDetail.tsx
> +    await updateDataset({
Add `try/catch`?

2021-11-15 03:38 UTC, neighborhood999 commented on packages/client/src/containers/Datasets/DatasetDetail.tsx
> +      // TODO: add doc link
Don't forget to put the link here if `tipsLink` is ready xd

2021-11-15 03:38 UTC, neighborhood999 commented on packages/client/src/containers/Datasets/DatasetDetail.tsx
> +          message: `Dataset '${dataset.name}' (${dataset.id}) has been updated.`,
How about this way?
```suggestion
          message: <>Dataset <b>{dataset.name} ({dataset.id})</b> has been updated.<>,
```

2021-11-15 04:14 UTC, neighborhood999 approved these changes

2021-11-15 04:23 UTC, merged