Feature/ch12332/job show resource information in job submission
InfuseAI/primehub-console pull request #82
Opened 2020-09-20 22:10 UTC by aar0nTw

### New feature: resource using status (ch12298 and ch10724)
### What's new
- Add ResourceStatus type in graphql.
- Add property `resourceStatus` on `Group` type.
- Add new component `ResourceMonitor`.
- Attach `ResourceMonitor` on `job/createForm` and `modelDeployment/createForm`.
- Small UI tweak for consistenly.

<img width="1265" alt="Screen Shot 2020-09-21 at 5 20 56 AM" src="https://user-images.githubusercontent.com/935988/93723343-62592480-fbd0-11ea-9234-793f6361cc57.png">
<img width="1265" alt="Screen Shot 2020-09-21 at 5 19 51 AM" src="https://user-images.githubusercontent.com/935988/93723320-3b025780-fbd0-11ea-85a1-bd450a13e565.png">
<img width="1079" alt="Screen Shot 2020-09-21 at 6 06 27 AM" src="https://user-images.githubusercontent.com/935988/93723366-992f3a80-fbd0-11ea-928a-131bdfd1504c.png">

2020-09-21 05:09 UTC, popcornylu commented
My usage metrics are different.

Jupyterhub
![image](https://user-images.githubusercontent.com/860633/93734354-8e45cb80-fc0b-11ea-9160-08ab72143ee9.png)
Job
![image](https://user-images.githubusercontent.com/860633/93734371-9ef64180-fc0b-11ea-8267-9db3e6c17687.png)

2020-09-21 05:12 UTC, popcornylu commented
In model deployment page, there is no user quota (it is correct). But dataset is not used here. Can we remove it? (or it is confusing for model deployment only installation)

![image](https://user-images.githubusercontent.com/860633/93734508-12984e80-fc0c-11ea-916b-5c2361009e7e.png)

2020-09-21 13:04 UTC, aar0nTw commented
pop, pls use `ch12332-2e71e27b` for update

2020-09-22 05:25 UTC, popcornylu requested changes
Two minor update required.

Please revert the two files.
packages/client/src/containers/mainPage.tsx
packages/client/src/context/group.tsx

2020-09-22 05:25 UTC, popcornylu commented on packages/client/src/containers/mainPage.tsx
> +    quotaCpu
Should we remove these? I think we don't use them anymore.

2020-09-22 05:25 UTC, popcornylu commented on packages/client/src/context/group.tsx
> +  quotaCpu: string;
We don't need them.

2020-09-22 05:40 UTC, popcornylu commented
LGTM

2020-09-22 05:40 UTC, merged